name: Daily SWE Job Search
on:
  schedule:
    - cron: '0 12 * * *'
  
  workflow_dispatch:
    inputs:
      search_query:
        description: 'Custom search query (optional)'
        required: false
        default: ''
        type: string

jobs:
  search-internships:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run job search
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        SEND_TO: ${{ secrets.SEND_TO }}
        CUSTOM_QUERY: ${{ github.event.inputs.search_query }}
      run: |
        echo "Starting automated job search with Google Custom Search..."
        echo "Current time: $(date)"
        echo "Running on: $RUNNER_OS"
        python job_finder.py
        echo "Job search completed!"
        
    - name: Upload logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: job-search-logs-${{ github.run_id }}
        path: |
          *.log
          error.txt
        retention-days: 7